#### Data Structures for Algebra 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch

### Scalers (Rank 0 tensors)

In [2]:
x = 25
y = 3
x+y

28

In [3]:
x = 25.0
y = 3 
x+y

28.0

### Scalers in PyTorch

In [4]:
x = torch.tensor(25) 
x

tensor(25)

In [5]:
x.shape                 #bcause scaler has no dimensionality

torch.Size([])

### Scalers in Tensorflow

In [6]:
import tensorflow as tf

In [7]:
x_tf = tf.Variable(25,dtype = tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [8]:
x_tf.shape                #no dimensionality

TensorShape([])

In [9]:
y_tf = tf.Variable(3,dtype = tf.int16)

In [10]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [11]:
tf_sum = tf.add(x_tf,y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [12]:
tf_sum.numpy()

28

In [13]:
type(tf_sum.numpy())

numpy.int16

In [14]:
z_tf = tf.Variable(3,dtype = tf.float16)
z_tf

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=3.0>

###  Vectors (Rank 1 Tensors) in NumPy

In [15]:
import numpy as np

In [16]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [17]:
x.shape

(3,)

In [18]:
len(x)

3

In [19]:
type(x)

numpy.ndarray

### Vector Tranposition

In [20]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [21]:
x.shape

(3,)

In [22]:
# transposing a regular 1-D array has no-effect
x_t = x.T
x_t

array([1, 2, 3])

In [23]:
x_t.shape

(3,)

In [24]:
# but it does we use nested "matrix-style" brackets
y = np.array([[4,5,6]]) 
y

array([[4, 5, 6]])

In [25]:
y.shape

(1, 3)

In [26]:
#transpose of a matrix with dimensional length 1 which is mathematically equalent 
y_t = y.T
y_t

array([[4],
       [5],
       [6]])

In [27]:
y_t.shape

(3, 1)

In [28]:
y_t.T

array([[4, 5, 6]])

In [29]:
y_t.T.shape

(1, 3)

### ZERO Vectors
#### have no effect if added to another vector

In [30]:
z = np.zeros(4)
z

array([0., 0., 0., 0.])

### *L²* Norm

In [31]:
import numpy as np

In [32]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [33]:
(1*1+2*2+3*3)**(1/2)

3.7416573867739413

In [34]:
np.linalg.norm(x)

3.7416573867739413

### _L¹_ Norm 

In [35]:
np.abs(1)+np.abs(2)+np.abs(3)

6

### Squared _L²_ Norm

In [36]:
1**2 + 2**2 + 3**2

14

In [37]:
np.dot(x,x)

14

#### Max Norm

In [38]:
np.max([np.abs(1),np.abs(2),np.abs(3)])

3

### Matrices (Rank 2 Tensors) in numpy

In [39]:
X = np.array([[1,2],[2,4],[5,7]])
X

array([[1, 2],
       [2, 4],
       [5, 7]])

In [40]:
X.shape

(3, 2)

In [41]:
X.size        #total elements in the array

6

In [42]:
#select left column of the index
X[:,0]

array([1, 2, 5])

In [43]:
#select the middle row
X[1,:]

array([2, 4])

In [44]:
X[0:2,0:2]

array([[1, 2],
       [2, 4]])

### Matrices in PyTorch

In [45]:
import torch

In [46]:
x_pt = torch.tensor([[1,2],[4,6],[6,9]])
x_pt

tensor([[1, 2],
        [4, 6],
        [6, 9]])

In [47]:
x_pt.shape

torch.Size([3, 2])

In [48]:
x_pt[1,:]

tensor([4, 6])

### Matrices in tensorflow

In [49]:
import tensorflow as tf

In [50]:
x_tf = tf.Variable([[1,2],[3,4],[9,0]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [9, 0]])>

In [51]:
tf.rank(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [52]:
x_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

### Common Tensor Operations

### Tensor Tranposition

In [53]:
X = np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [54]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [55]:
tf.transpose(x_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 9],
       [2, 4, 0]])>

In [56]:
x_pt.T

tensor([[1, 4, 6],
        [2, 6, 9]])

### Basic Tensor Arithmetic

In [57]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [58]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [59]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [60]:
x_pt

tensor([[1, 2],
        [4, 6],
        [6, 9]])

In [61]:
x_pt*2

tensor([[ 2,  4],
        [ 8, 12],
        [12, 18]])

In [62]:
x_pt*2 + 2

tensor([[ 4,  6],
        [10, 14],
        [14, 20]])

In [63]:
torch.add(torch.mul(x_pt,2),2)

tensor([[ 4,  6],
        [10, 14],
        [14, 20]])

### Hadamard Product or Elementwise Product

In [64]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [65]:
A = X + 2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [66]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [67]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [68]:
x_tf 

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [9, 0]])>

In [69]:
A_tf = x_tf + 2
A_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 5,  6],
       [11,  2]])>

In [70]:
x_tf + A_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 8, 10],
       [20,  2]])>

In [71]:
x_tf * A_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  8],
       [15, 24],
       [99,  0]])>

In [72]:
x_pt

tensor([[1, 2],
        [4, 6],
        [6, 9]])

In [73]:
A_pt = x_pt + 2
A_pt

tensor([[ 3,  4],
        [ 6,  8],
        [ 8, 11]])

In [74]:
x_pt + A_pt

tensor([[ 4,  6],
        [10, 14],
        [14, 20]])

In [75]:
x_pt * A_pt

tensor([[ 3,  8],
        [24, 48],
        [48, 99]])

### Reduction

In [76]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [77]:
X.sum()

68

In [78]:
x_pt

tensor([[1, 2],
        [4, 6],
        [6, 9]])

In [79]:
x_pt.sum()

tensor(28)

In [80]:
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [9, 0]])>

In [81]:
torch.sum(x_pt)

tensor(28)

In [82]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [83]:
X.sum(axis = 0) #row wise sum

array([33, 35])

In [84]:
X.sum(axis = 1) #column wise sum

array([27, 31, 10])

In [85]:
x_pt

tensor([[1, 2],
        [4, 6],
        [6, 9]])

In [86]:
torch.sum(x_pt,0)

tensor([11, 17])

In [87]:
torch.sum(x_pt,1)

tensor([ 3, 10, 15])

In [88]:
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [9, 0]])>

In [89]:
tf.reduce_sum(x_tf,1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 7, 9])>

### Dot Product

In [90]:
x

array([1, 2, 3])

In [91]:
y = np.array([0,1,2])
y

array([0, 1, 2])

In [92]:
np.dot(x,y)

8

In [93]:
x_pt = torch.tensor([25,2,5]) 
x_pt

tensor([25,  2,  5])

In [94]:
y_pt = torch.tensor([0,1,2])
y_pt

tensor([0, 1, 2])

In [95]:
np.dot(x_pt,y_pt)

12

In [96]:
x_tf = tf.Variable([25,2,5])

In [97]:
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>

In [98]:
y_tf = tf.Variable([0,1,2])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2])>

In [99]:
tf.reduce_sum(tf.multiply(x_tf,y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=12>

## Matrix Properties

### Frobenius Norm

In [100]:
import numpy as np

In [101]:
X = np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [102]:
(1**2 + 2*2 + 3*3 + 4*4)**(1/2)

5.477225575051661

In [103]:
np.linalg.norm(X) #Same function as for L2 Norm

5.477225575051661

In [104]:
import torch

In [105]:
X_pt = torch.tensor([[1,2],[3,4.]])  #torch.norm() requires float type
torch.norm(X_pt)

tensor(5.4772)

In [106]:
import tensorflow as tf

In [107]:
X_tf = tf.Variable([[1,2],[3,4.]]) #tf.norm() also required floats
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.477226>

### Matrix multiplication with Vector

In [108]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
b = np.array([1,2])
b

array([1, 2])

In [110]:
np.dot(A,b)

array([ 5, 11, 17])

In [111]:
A_pt = torch.tensor([[1,2],[3,4],[5,6]])
b_pt = torch.tensor([1,2])
torch.matmul(A_pt,b_pt)

tensor([ 5, 11, 17])

In [112]:
A_tf = tf.Variable([[1,2],[3,4],[5,6]])
b_tf = tf.Variable([1,2])
tf.linalg.matvec(A_tf,b_tf) 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 11, 17])>

### Matrix Multiplication (with two matrices)

In [113]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [114]:
B = np.array([[1,2],[3,4]])
B

array([[1, 2],
       [3, 4]])

In [115]:
np.dot(A,B)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [116]:
#np.dot(B,A)

In [117]:
A.shape

(3, 2)

In [118]:
B.shape

(2, 2)

In [119]:
B_pt = torch.from_numpy(B)    #much cleaner than tf conversion
B_pt

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [120]:
B_pt = torch.tensor([[1,2],[9,0]]).T # another neat way to create tensor with tranposition
B_pt

tensor([[1, 9],
        [2, 0]])

In [121]:
torch.matmul(A_pt,B_pt)

tensor([[ 5,  9],
        [11, 27],
        [17, 45]])

In [122]:
tf.matmul(A_pt,B_pt)  #multiply for matrix by matrix

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 5,  9],
       [11, 27],
       [17, 45]], dtype=int64)>

In [123]:
B

array([[1, 2],
       [3, 4]])

In [124]:
B_tf = tf.convert_to_tensor(B,dtype = tf.int32)
B_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### Symmetric Matrix

In [125]:
import numpy as np

In [126]:
x_sym = np.array([[0,1,2],[1,7,8],[2,8,9]])
x_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [127]:
x_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [128]:
x_sym == x_sym.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Identity Matrix 

In [129]:
import torch

In [130]:
I = torch.tensor([[1,0,0],[0,1,0],[0,0,1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [131]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [132]:
torch.matmul(I,x_pt)

tensor([25,  2,  5])

### Matrix Inversion

In [133]:
import numpy as np

In [134]:
X = np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [135]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [136]:
y = np.array([4,-7])
y

array([ 4, -7])

In [137]:
w = np.dot(Xinv,y)
w

array([-1.,  4.])

### to show that y = _Xw_

In [138]:
np.dot(X,w)

array([ 4., -7.])

In [139]:
y

array([ 4, -7])

### Matrix inversion where no solution 

In [140]:
X = np.array([[-2,4],[-4,8]])
X

array([[-2,  4],
       [-4,  8]])

In [141]:
#Xinv = np.linalg.inv(X)
#Xinv

In [142]:
X = np.array([[-2,4],[-2,4]])
X

array([[-2,  4],
       [-2,  4]])

In [143]:
#Xinv = np.linalg.inv(X)
#Xinv